import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { languages } from "@/i18n/settings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata({ params }: { params: { lng: string } }): Promise<Metadata> {
  const { lng } = await params;
  
  // Create alternates object for hreflang
  const alternates: Record<string, string> = {};
  languages.forEach(language => {
    alternates[language] = `/${language}`;
  });
  alternates['x-default'] = `/en`;

  return {
    title: "Create Next App",
    description: "Generated by create next app",
    alternates: {
      languages: alternates
    }
  };
}

export async function generateStaticParams() {
  return languages.map(lng => ({ lng }));
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lng: string }>;
}>) {
  const { lng } = await params;
  return (
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      lang={lng}
    >
      {children}
    </body>
  );
} 